### ISSUE TITLE
Sync9 breaks inconsistently depending on whether patches are separated into different versions or not

### ISSUE THREAD

**Issue by brynbellomy** [dglittle/cdn#3]
With these patches:
```js
var p1 = `. = {"permissions":{"*":{"^.*$":{"read":true,"write":false}},"96216849c49358b10257cb55b28ea603c874b05e":{"^.*$":{"read":true,"write":true}}},"providers":["localhost:21231","localhost:21241"]}`
var p2 = `.shrugisland = {}`
var p3 = `.shrugisland.talk0 = {}`
```
This breaks:
```js
var x = sync9_create()
sync9_add_version(x, 'p1', {}, [p1])
sync9_add_version(x, 'p2', {p1: true}, [p2, p3])
```
But this does not:
```js
var x = sync9_create()
sync9_add_version(x, 'p1', {}, [p1])
sync9_add_version(x, 'p2', {p1: true}, [p2])
sync9_add_version(x, 'p3', {p2: true}, [p3])
```

**Comment by toomim** [comment]
Patches are interpreted with respect to their parent version; not the set of patches applied so far. (The set of patches at a version have no implied order, in fact.)

In other words, time occurs in versions. If two patches occur in the same version, they occur at the same time, and there is no ordering amongst them.

Since the patch `p3` depends on `p2`, it has to occur after `p2`, which means in a subsequent version.

**Comment by toomim** [comment]
This is a design decision we made solidly 1 or 2 years ago. Lemme know if you want me to recall the  rationale.

**Comment by brynbellomy** [comment]
Makes perfect sense.

**Comment by toomim** [comment]
Ok.

I do feel these kinds of design decisions are a lot more satisfying to talk about when the rationale is presented along with them, so that you can agree or disagree. :-/

A lot of systems (like ShareJS/ShareDB) have chosen the other approach, and made multiple patches at a version dependent on the patches that came before.
